import { describe, it, expect, beforeEach } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  loadDescriptions, writeDescriptions, pathForKind, isFresh, generatedLabel, KINDS,
} from './store.mjs';

const row = (over = {}) => ({
  targetId: 'domain:checkout',
  kind: 'domain',
  contentHash: 'abc',
  text: 'The checkout flow.',
  model: 'fake-model',
  provider: 'command',
  generatedAt: '2026-08-17T10:00:00.000Z',
  ...over,
});

let cache;
beforeEach(() => {
  cache = mkdtempSync(join(tmpdir(), 'lg-desc-store-'));
});

describe('description store', () => {
  it('round-trips rows through a per-kind JSONL file', () => {
    writeDescriptions(cache, 'domain', [row(), row({ targetId: 'domain:cart', text: 'The cart.' })]);
    const loaded = loadDescriptions(cache);
    expect(loaded.size).toBe(2);
    expect(loaded.get('domain:checkout')).toMatchObject({ text: 'The checkout flow.', model: 'fake-model' });
    expect(loaded.byKind('domain')).toHaveLength(2);
  });

  it('writes one file per kind and never crosses them', () => {
    writeDescriptions(cache, 'domain', [row()]);
    writeDescriptions(cache, 'file', [row({ targetId: 'file:src/a.ts', kind: 'file' })]);
    expect(existsSync(pathForKind(cache, 'domain'))).toBe(true);
    expect(existsSync(pathForKind(cache, 'file'))).toBe(true);
    expect(existsSync(pathForKind(cache, 'symbol'))).toBe(false);
    expect(readFileSync(pathForKind(cache, 'domain'), 'utf8')).not.toContain('src/a.ts');
  });

  it('merges over existing rows and leaves untouched ones alone', () => {
    writeDescriptions(cache, 'domain', [row(), row({ targetId: 'domain:cart', text: 'old cart' })]);
    writeDescriptions(cache, 'domain', [row({ targetId: 'domain:cart', text: 'new cart', contentHash: 'zzz' })]);
    const loaded = loadDescriptions(cache);
    expect(loaded.get('domain:cart')).toMatchObject({ text: 'new cart', contentHash: 'zzz' });
    expect(loaded.get('domain:checkout').text).toBe('The checkout flow.');
  });

  it('is byte-deterministic regardless of write order', () => {
    writeDescriptions(cache, 'domain', [row({ targetId: 'domain:b' }), row({ targetId: 'domain:a' })]);
    const first = readFileSync(pathForKind(cache, 'domain'), 'utf8');
    const other = mkdtempSync(join(tmpdir(), 'lg-desc-store2-'));
    writeDescriptions(other, 'domain', [row({ targetId: 'domain:a' }), row({ targetId: 'domain:b' })]);
    expect(readFileSync(pathForKind(other, 'domain'), 'utf8')).toBe(first);
  });

  it('prunes rows whose target no longer exists when keepIds is given', () => {
    writeDescriptions(cache, 'domain', [row(), row({ targetId: 'domain:gone' })]);
    const res = writeDescriptions(cache, 'domain', [], { keepIds: new Set(['domain:checkout']) });
    expect(res.pruned).toBe(1);
    expect(loadDescriptions(cache).get('domain:gone')).toBeUndefined();
    expect(loadDescriptions(cache).get('domain:checkout')).toBeDefined();
  });

  it('survives a corrupt line and a missing directory', () => {
    expect(loadDescriptions(join(cache, 'nope')).size).toBe(0);
    mkdirSync(join(cache, 'descriptions'), { recursive: true });
    writeFileSync(pathForKind(cache, 'domain'), `not json\n${JSON.stringify(row())}\n{"targetId":"x"}`);
    const loaded = loadDescriptions(cache);
    expect(loaded.size).toBe(1);
    expect(loaded.get('domain:checkout')).toBeDefined();
  });

  it('isFresh compares the content hash, not the text', () => {
    expect(isFresh(row(), { contentHash: 'abc' })).toBe(true);
    expect(isFresh(row(), { contentHash: 'different' })).toBe(false);
    expect(isFresh(undefined, { contentHash: 'abc' })).toBe(false);
  });

  it('generatedLabel always names the model, the provider and the date', () => {
    expect(generatedLabel(row())).toBe('generated by fake-model via command, 2026-08-17');
    expect(generatedLabel({})).toContain('unspecified model');
    expect(generatedLabel({})).toContain('unknown provider');
  });

  it('KINDS covers exactly the three describable kinds', () => {
    expect(KINDS).toEqual(['domain', 'file', 'symbol']);
  });
});
